version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    volumes:
      - ./project:/app
      - /dev/bus/usb:/dev/bus/usb
    command: sh -c 'make && make flash'
